### ISSUE TITLE
Manually send shutdown event or customize constants

### ISSUE THREAD

**Issue by d1skort** [eht16/python-logstash-async#13]
Hi!

First of all, I want to say thank you for your library. It helps me a lot :)

But I have some problem here: sometimes I want to manually push all messages from database to logstash

Maybe, ability to customize constants (from constants.py) would help me, idk

I can do PR, if you say me, what solution the better, by your opinion

**Comment by eht16** [comment]
What exactly do you suggest?
Do you want to signal your running application from outside somehow to trigger pushing all pending events?
I didn't get what you mean by customizing any constants in this regard.

**Comment by d1skort** [comment]
Yeap, exactly!

By customising constants I meant pass them to Handler constructor, cause QUEUED_EVENTS_FLUSH_INTERVAL = 10.0, for example, not suitable for me

**Comment by eht16** [comment]
I do want to make the constants configurable in some way, not yet completely sure how but it's on my roadmap.
So you just want to reduce or increase the flush interval?
I got your initial request as if you want to trigger the flush completely manually (either from your application or from completely external)? For the former case would be easy, we just need to add a public API to `LogProcessingWorker` to execute the flush logic.
I think this is quite reasonable. If you can wait a few days and this helps in your use case, I'll implement this.
