### ISSUE TITLE
logstash-async ignoring formatter options

### ISSUE THREAD

**Issue by kostrahb** [eht16/python-logstash-async#17]
I have encountered a problem, logstash logger seems to totally ignore formatter options when I create my own formatter with custom options. To be precise I can pass formatter to logger (It might be a little bit obscure way but I was inspired by logstash-async implementation itself) and as it prints correct value it seems to became part of logger. But on the other side, in logstash I can only see the default `"type" => "python-logstash"` in the message. 
```
#!/usr/bin/python

import logging
import sys
from logstash_async.handler import AsynchronousLogstashHandler
from logstash_async.formatter import LogstashFormatter

host = 'localhost'
port = 5959

test_logger = logging.getLogger('test')

test_formatter = LogstashFormatter(message_type='abcd', tags=None, fqdn=False, extra_prefix='new', extra=None)
test_logger.formatter = test_formatter

test_logger.setLevel(logging.INFO)
test_logger.addHandler(AsynchronousLogstashHandler(
    host, port, database_path='logstash.db'))

print test_logger.formatter._message_type

test_logger.warning('Test logstash warning message.')
```

**Comment by atomberg** [comment]
I just ran into the same issue today.

If you look at the `AsynchronousLogstashHandler`'s code, it *never* sets its own formatter. Therefore, the formatter of the logger is not inherited by the handler.

Try doing this hack instead:
```python
test_formatter = LogstashFormatter(message_type='abcd', tags=None, fqdn=False, extra_prefix='new', extra=None)
test_logger.handlers[0].formatter = test_formatter
```
By replacing the handler's formatter directly, you make logstash receive the correct `"type" => "abcd"`.

**Comment by eht16** [comment]
Calling `handler.setFormatter()` should work, doesn't it?
Is setting the formatter on a logger instance generally supported and commonly used? I can't remember to have seen this.

**Comment by kostrahb** [comment]
Well, I have tried this approach as a last resort because `handler.setFormatter()` unfortunately yields
```
Traceback (most recent call last):
  File "./logstash.py", line 14, in <module>
    test_logger.setFormatter(test_formatter)
AttributeError: 'Logger' object has no attribute 'setFormatter'
```

**Comment by atomberg** [comment]
@kostrahb You called `.setFormatter` on the __logger__ instance, calling it on the __handler__ instance works fine.

@eht16 It is hard to say what is commonly used.

The [Python Logging Cookbook](https://docs.python.org/3/howto/logging-cookbook.html#multiple-handlers-and-formatters) does set fomatters for each handler using the `setFormatter` method. Personally, I think that using a logging configuration passed to `dictConfig` is the best way, and the current implementation of `AsynchronousLogstashHandler` works fine with that.

You should probably mark this as closed. Thanks for making this module!

**Comment by eht16** [comment]
> It is hard to say what is commonly used.

Yeah, for me as well hence the question :).
I agree using `dictConfig` or a logging configuration file is probably easier and at least what I use in private projects as well as at work and so I didn't had to set up the logging framework manually for a long time. Thanks to `dictConfig`.
