### ISSUE TITLE
Gunicorn logging support

### ISSUE THREAD

**Issue by SalahAdDin** [eht16/python-logstash-async#20]
Hi, 
I just came to this package because the original isn't working very well.

I wan't to know if i can use this package for log `gunicorn`.

I did the next config file:
```
[loggers]
keys=root, logstash.error, logstash.access

[handlers]
keys=console , logstash

[formatters]
keys=generic, access, json

[logger_root]
level=INFO
handlers=console

[logger_logstash.error]
level=INFO
handlers=logstash
propagate=1
qualname=gunicorn.error

[logger_logstash.access]
level=INFO
handlers=logstash
propagate=0
qualname=gunicorn.access

[handler_console]
class=StreamHandler
formatter=generic
args=(sys.stdout, )

[handler_logstash]
class=logstash_async.handler.AsynchronousLogstashHandler
formatter=json
version=1
args=('logstash',5959, 'logstash.db')

[formatter_generic]
format=%(asctime)s [%(process)d] [%(levelname)s] %(message)s
datefmt=%Y-%m-%d %H:%M:%S
class=logging.Formatter

[formatter_access]
format=%(message)s
class=logging.Formatter

[formatter_json]
class=pythonjsonlogger.jsonlogger.JsonFormatter
```

As you can see i only change the `logstash` handler by this handler and i added the missing argument `data_base`.

Can you make some documentation about it?

Thank you.

**Comment by eht16** [comment]
Is there any problem with the posted configuration or was it just meant as an example of a working configuration for the docs?

Adding a configuration sample using a logging config file is a good idea and will do soon.

**Comment by SalahAdDin** [comment]
This is my configuration file, it works very well, putting in documentation it's a good idea, i think.

**Comment by eht16** [comment]
http://python-logstash-async.readthedocs.io/en/latest/usage.html#usage-with-logging-file-config

Thanks.
