### ISSUE TITLE
Logs have not been sent in high rate 

### ISSUE THREAD

**Issue by nnehdi** [eht16/python-logstash-async#22]
Our system logs with more that 10,000 logs/Sec and with this rate logs are not sent in logstash. When we check caching database file size we understand that it is increasing with time and its size gets more than 1 gigs.
What can we do about it? Is there any config about it? Is it possibe that it's logstash overloading problem?

**Comment by eht16** [comment]
- are logs shipped to and processed by Logstash with lower rates? Maybe use a test setup with the same configuration but with a lower log rate just to ensure the basic setup (your application -> logstash-async -> Logstash) does work at all

- database size: the used database is Sqlite and the database files usually keep the file size even if the contents got deleted. You could try to execute `sqlite3 logstash.db VACUUM` which should reduce the size of the database file to the contents. Alternatively, check with `sqlite3 logstash.db "select count(event_id) from event;"` how many events are stored in the Sqlite database. If it is zero or a low number, the VACUUM command should help, if you see a very high number, this indicates a general problem in your setup in that logstash-async was not able to deliver the events to Logstash. In this case you should find errors in the logs of logstash-async.

There is no configuration to tune the database or change its behaviour except disabling buffering events in the database and use a in-memory queue instead. For details about this, see http://python-logstash-async.readthedocs.io/en/latest/persistence.html and http://python-logstash-async.readthedocs.io/en/latest/config.html.

**Comment by nnehdi** [comment]
Yes. Logstash works in low rate correctly with negligible delay. But in higher rate at first we have logs but it decreases with time until it becomes zero.
Yes, I have already read the mentioned links. What should be the database_path of the AsynchronousLogstashHandler constructor to use in-memory queue.
If I set database_path to empty string what happens?
tnx

**Comment by eht16** [comment]
Just pass `None` or an empty string for `database_path` to enable the in-memory queue.
I made this a bit clearer in https://github.com/eht16/python-logstash-async/commit/0c467c6d1b9f47eaca632233575eb51928406fff.

After thinking a bit more about it, your lags might result from https://github.com/eht16/python-logstash-async/blob/master/logstash_async/database.py#L115: here all events are fetched and their status is updated to mark them as 'currently being processed' though we need to issue multiple queries if there are many events as with Sqlite there is a limit of 1000 values you can use within a single query.
To honor this limit, I added chunked updating with a chunk size of 750 events per update.
In your case, it might be that issuing the multiple update statements to the database is the bottleneck and during their execution more new events are received and so processing gets too slow.

If this assumption is true, using the in-memory queue shoud immediately solve the problems. I'm not sure whether the Sqlite limitation can be workarounded or even solved in a more clever way.
Maybe even using Sqlite as a "buffer" isn't suitable at all for that rate of events.
