### ISSUE TITLE
Clarify documentation for extra dictionaries

### ISSUE THREAD

**Issue by shidarin** [eht16/python-logstash-async#23]
Reading the documentation, I initially thought I could simply pass an extra kwarg to AsynchronousLogstashHandler:

"You can also specify an additional extra dictionary in the logging configuration with static values like the application name, environment, etc. These values will be merged with any extra dictionary items passed in the logging call into the configured extra prefix."

But the [docs](http://python-logstash-async.readthedocs.io/en/latest/usage.html) must mean the Logging File Config. They don't mention using a LoggingAdapter- which is the other way I know of to do this. It'd be neat to have an example of this in the docs, since I think adding extras to the Logger as a whole is a use case just as large as adding them to individual calls.

Thanks for your work on python-logstash-async!

**Comment by eht16** [comment]
The `extra` kwarg is meant to be passed the formatter, not the handler.

I added some example code in https://github.com/eht16/python-logstash-async/pull/26, do you think this is enough?

**Comment by shidarin** [comment]
#26 looks great, thanks a ton!
