### ISSUE TITLE
message_type not being set

### ISSUE THREAD

**Issue by marciogarcianubeliu** [eht16/python-logstash-async#28]
I have a Django Server, I was using python-logstash with UDP, now I change my script to use this one with SSL, it's working pretty well, but the message_type is not being set.

I tried everything, I can see all the values being set in the config, but in Logstash I'm still seeing python-logstash as type.

Anything I can do to solve this?

**Comment by eht16** [comment]
Just tested and it works for me.
Can you post the relevant part of your config?

Or compare your config to the following snippet which should work:
```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'logstash': {
            '()': 'logstash_async.formatter.DjangoLogstashFormatter',
            'message_type': 'customer-message-type',
            'fqdn': False, # Fully qualified domain name. Default value: false.
            'extra_prefix': 'py',
            'extra': [...]
        }
    }
[...]
```

**Comment by marciogarcianubeliu** [comment]
I did a compare with you config snippet and using the GitHub config, but doesn't work either :-(

My config is:

```
    'loggers': {
        'django.request': {
            'level': 'INFO', 
            'propagate': True, 
            'handlers': ['logstash']
        }, 

[...]

    'disable_existing_loggers': False, 
    'version': 1, 
    'formatters': {
        'verbose': {
            'datefmt': '%Y-%m-%d %H:%M:%S', 
            'format': '[%(asctime)s] %(levelname)s %(message)s'
        }, 
        'logstash': {
            '()': 'logstash_async.formatter.DjangoLogstashFormatter', 
            'message_type': 'logstash-test'
        }
    }, 

[...]
'handlers': {
        'logstash': {
            'host': 'X.X.X.X', 
            'certfile': 'logstash.crt', 
            'ssl_enable': True, 
            'ssl_verify': False, 
            'database_path': 'logstash.db', 
            'keyfile': 'logstash.key', 
            'class': 'logstash_async.handler.AsynchronousLogstashHandler', 
            'transport': 'logstash_async.transport.TcpTransport', 
            'port': 5959
        }, 
[...]

    'root': {
        'handlers': ['console', 'logstash'], 
        'level': 'INFO'
    }


```

With this config I can see all the messages in Kibana, only the message_type (type field) was not being set.

**Comment by marciogarcianubeliu** [comment]
I figure out what I'm doing wrong (or not documented :-D ) ...

In the handler I need to set:

`'formatter': 'logstash'`


After that, its working :-)

Thank you so much!

**Comment by eht16** [comment]
Glad to hear it works now.
JFTR, the formatter option on handlers is not special to python-logstash-async, it's part of the logging framework. Anyway, I'll add the `formatter` option to the example in the docs in the next days.
