### ISSUE TITLE
Big database prevents treating events

### ISSUE THREAD

**Issue by mzominy** [eht16/python-logstash-async#31]
Hi, thanks for the great work on the lib!

If the database gets too big, (witnessed with 30k lines of big logs (about 1k chars each)), there is a timeout on the connection when sending logs to logstash with TCP. The timeout creates an exception preventing the logs from being removed from the local database, although **logstash still streats the logs he receives before the timeout!**

This got us stuck in a loop of the same logs being processed by logstash over and over again! We avoided the problem by adding a 'LIMIT 100' on the query that gets the logs out of the DB, it works because it fits our data and connection. Maybe a cleaner fix would be to try with the whole database and if you get a 'timeout' try with a smaller portion of the DB and etc. until you can finally send your logs.

I don't need a fix, it's to let you and other users know of the issue.

Regards.

**Comment by eht16** [comment]
Thanks for the report.

Alternatively to adding a limit to the database query, you could try to increase the timeout in the constants module. So you don't have to modify the package's code, still it is just a workaround.

It would be easy to change the code to mark events as submitted in case of timeouts. Though this might not always be correct, depending on when and why the timeout occurred. There is probably no real fix for this problem as with the TCP transport we get no feedback at all from Logstash whether the data arrived and were processed correctly.

As the docs state, the solution would be to switch to the Beats protocol which provides an ACK message sent by Logstash after it received all of the data.
This should make the situation a lot better for many cases.

Unfortunately, https://github.com/elastic/logstash-forwarder/blob/master/PROTOCOL.md is still the only available protocol documentation and it's for the "old" Lumberjack protocol.
However, I found https://github.com/brxie/PyLumberjack which implements this protocol and I managed to adopt it to the Lumberjack protocol V2 which seems to be equal to the Beats protocol even if I couldn't any details except studying the Ruby and Java source code of the client and senders and the fact that the Logstash documentation actually states one can use the Lumberjack output plugin to send to the Beats input plugin (https://www.elastic.co/guide/en/logstash/current/ls-to-ls.html).

Conclusion: I successfully sent events from the modified Python Lumberjack implementation to Logstash' Beats input plugin. Still need to polish the code a bit but then we can add Beats as transport protocol here.

**Comment by eht16** [comment]
Finally, I've found time to finish https://github.com/eht16/pylogbeat and now it is integrated here.
Additionally, I added a constant for the "hack" you did: constants.QUEUED_EVENTS_BATCH_SIZE
So you can configure the batch size as you like (the default is 50).

Docs:
https://python-logstash-async.readthedocs.io/en/stable/config.html#options-for-the-asynchronous-processing-and-formatting

I think with the new setting and the Beats transport, your problems should get better.
