### ISSUE TITLE
Random Timeouts

### ISSUE THREAD

**Issue by suvari3V** [eht16/python-logstash-async#34]
I am experiencing timeout exceptions from time to time like

```
19/02/05 13:49:53 - ERROR - An error occurred while sending events: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/logstash_async/worker.py", line 118, in _fetch_events
    self._fetch_event()
  File "/usr/local/lib/python3.7/dist-packages/logstash_async/worker.py", line 140, in _fetch_event
    self._event = self._queue.get(block=False)
  File "/usr/lib/python3.7/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/logstash_async/worker.py", line 224, in _flush_queued_events
    self._send_events(events)
  File "/usr/local/lib/python3.7/dist-packages/logstash_async/worker.py", line 255, in _send_events
    self._transport.send(events, use_logging=use_logging)
  File "/usr/local/lib/python3.7/dist-packages/logstash_async/transport.py", line 37, in send
    self._send(events)
  File "/usr/local/lib/python3.7/dist-packages/logstash_async/transport.py", line 54, in _send
    self._send_via_socket(event)
  File "/usr/local/lib/python3.7/dist-packages/logstash_async/transport.py", line 136, in _send_via_socket
    self._sock.sendall(data_to_send)
socket.timeout: timed out
```
Could you suggest?

**Comment by eht16** [comment]
Sounds like #31.
Do you send large events or might your Logstash instance be the limiting end? Or maybe it's just a networking/firewalling issue.

Hard to say what's causing the timeouts without any further information.

You could try the new Beats transport or just tune some of the options as described in https://python-logstash-async.readthedocs.io/en/stable/config.html#options-for-the-asynchronous-processing-and-formatting.

**Comment by suvari3V** [comment]
Well I do not believe it is matter of too much events on my side. I am testing on local environment without too much pressure.
It is using internal network so network should not be the issue as well.
Firewall also does not apply here as for the purpose I tried to turn it off. Still the issue appear.
I will try with Beats transport.

**Comment by eht16** [comment]
If your Logstash is local and not loaded, then I'm out of ideas what could cause this :(.
I'm interested how it goes with the Beats transport.

**Comment by Mp-Pro** [comment]
@suvari3V i was facing the same issue but its just a warning in my case

 warning: An error occurred while sending events: timed out
 
 could you provide some insights what could the reason be.. or what i might be doing wrong..

**Comment by eht16** [comment]
Ideally you could open a new issue, this one is old and closed since four years.

The message above means that the Logstash server could not be reached within the configured timeout.
This might have numerous reasons, being a network problem or a firewall or the Logstash server did not respond in a timely manner.
It's hard to say what could be the cause without more information.
Does it happen always or just sometimes? 
Do you see any events in Logstash from the library?
Can you connect to the Logstash server using `telnet` or `netcat` on the same port?
