### ISSUE TITLE
Events stored in the DB is sent before 

### ISSUE THREAD

**Issue by JonasKs** [eht16/python-logstash-async#35]
If Logstash crashes, `python-logstash-async` is working perfectly, the events get stored in the sqlite database. How ever, when restarting the Logstash container, the connection is established, sent and deleted from the database instantly, but the Logstash is not ready to handle them. All the stored messages is then lost.

My workaround will be to have health checks before allowing traffic in to the container.

**Comment by eht16** [comment]
Yes but I think we can't do much here with the TCP transport. Logstash does not respond in any way to the messages sent, so we never know if they were processed sucessfully. This is a limitation of the TCP input in Logstash, not of this library.

Your workaround seems sensible to me, maybe it's worth to report this to Logstash. It should be possible to open the TCP input in Logstash first when it is also capable of processing events.

Another alternative would be to use the Beats transport (https://python-logstash-async.readthedocs.io/en/stable/config.html#options-for-configuring-the-log-handler), recently added in python-logstash-async, as with the Beats protocol, Logstash *will* acknowledge the received events.

**Comment by JonasKs** [comment]
Another workaround could be to do a 10-15 second timeout after connection before starting to sending logs too. Not sure if thats a wanted design choice to do, though. 

I'll look into the Beats transport, thank you.

**Comment by eht16** [comment]
I really don't want to add an arbitrary timeout before sending to Logstash.
IMO the problem is on the Logstash side and adding such quirks doesn't make it better.

**Comment by JonasKs** [comment]
Beats worked like a charm like you said, thank you.
