### ISSUE TITLE
[request] multiple hosts support

### ISSUE THREAD

**Issue by CameronNemo** [eht16/python-logstash-async#41]
Hello, and thank you for your well maintained fork.

One benefit of using something like filebeat is that it can fall back to a backup logstash host when the first one defined is unavailable. Do you have any recommendations on how to add this type of feature here, allowing for multiple host/port combos to be specified for the same log handler?

**Comment by ypid-geberit** [comment]
@CameronNemo Not sure what your use case is but in case of logging on Linux or Windows, you might want to log to journald (https://github.com/systemd/python-systemd) or the event log respectively and then use journalbeat or winlogbeat.

**Comment by CameronNemo** [comment]
Nak. Journalbeat has a lot of other issues, including missed messages due to buffering, lack of transparency across mount namespaces, log corruption, and a convoluted, type unaware structured log format.

**Comment by ypid-geberit** [comment]
@CameronNemo Thanks for your feedback. You are specifically talking about Journald and not journalbeat, is this correct?

In my tests logging to journald and then shipping them with journalbeat worked but I don’t have long-term experience with it yet as journalbeat is still new.

**Comment by eht16** [comment]
The primary intention of this implementation is to be resilient to network failures or a in some other way unreachable Logstash instance. This is achieved by retrying to transmit the events and persisting them until transferred successfully.

So in theory, it is not necessary to configure multiple Logstash instances as fallback.
In reality, this could still be useful to reduce overall transmission time.

I won't implement this myself but would accept a well written pull request.
