### ISSUE TITLE
Missing @medatadata[beat]

### ISSUE THREAD

**Issue by bngsudheer** [eht16/python-logstash-async#48]
This is when using the beats protocol.

I followed the common output pattern in logstsash:
```
output {
  elasticsearch {
    hosts => ["http://192.168.1.5:9200"]
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
  }
}

```
It seems `@metadata` is missing, therefore `@metadata[beat]` is missing. This configuration in logstash results in indexes like `  "%{[@metadata][beat]}-2020.05.25"`.

I would expect the index name to be something like my_beat_name-2020.05.25 for a standard output to elasticsearch.

It would be useful to add an example configuration in logstash pipeline to send data to elasticsearch.

**Comment by eht16** [comment]
I'm not completely sure what the problem is.
The metadata field exists only in Logstash (https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#metadata) and so I assume whatever you are missing, it is probably to be configured in Logstash.

**Comment by bngsudheer** [comment]
In the formatter we have:
```
 message = {
            '@timestamp': self._format_timestamp(record.created),
            '@version': '1',
            'host': self._host,
            'level': record.levelname,
            'logsource': self._logsource,
            'message': record.getMessage(),
            'pid': record.process,
            'program': self._program_name,
            'type': self._message_type,
        }
```
In the message dict, we need the key `beat`. The `beat` key is expected in common logstash beat input configuration. 

I think that will solve the problem. 

Here's a reference: https://www.elastic.co/guide/en/beats/metricbeat/current/logstash-output.html

**Comment by bngsudheer** [comment]
```output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "%{[@metadata][beat]}-%{[@metadata][version]}" 
  }
}```
This is a common configuration in logstash to send data to elasticsearch when receiving data from beats. Hence, I requested to have the 'beat` field in the metadata.

**Comment by eht16** [comment]
Well, you could achieve that by adding the `@metadata` field to the `extra` fields and use no `extra_prefix` so the additional fields will be placed on the top-level of the event:
```py
formatter = LogstashFormatter(extra_prefix=None, extra={'@metadata':{'beat': 'your-beat-name', 'version': 'whatever-version'})
```
Alternatively, you can subclass the `LogstashFormatter` class and customize it to your needs.

I'm not completely against adding a `@metadata` to the formatter in general, it just seem quite specific to me. The "common" configuration you talk about is only common for the various Beats products. Anyway, feel free to submit a well written PR for adding a `@metadata` argument to `LogstashFormatter`.

**Comment by bngsudheer** [comment]
Thanks. I will make some research to better understand this and will submit a PR if necessary.

**Comment by bngsudheer** [comment]
I did some tests. 

This worked:
```
formatter = LogstashFormatter(extra_prefix=None, extra={'@metadata':{'beat': 'your-beat-name', 'version': 'whatever-version'})
```
The next step is to make `@metadata` available in the `LogstashFormatter` itself. I am thinking of adding the key to https://github.com/eht16/python-logstash-async/blob/master/logstash_async/formatter.py#L91

Does it mean, you have to add `@metadata` to the constant FORMATTER_LOGSTASH_MESSAGE_FIELD_LIST?

**Comment by eht16** [comment]
Yes, otherwise the added `@metadata` field would be moved in the `extra` field structure.
