### ISSUE TITLE
The default value for database_path doesn't work

### ISSUE THREAD

**Issue by leifurhauks** [eht16/python-logstash-async#5]
The default value for database_path, `:memory:`, currently doesn't work with this library because every connection to `:memory:` creates a separate in-memory database. I suggest either providing a generic filename for an on-disk database file, such as `log_event_queue.sqlite3`, or making the `database_path` argument to `AsynchronousLogstashHandler` required.

**Comment by eht16** [comment]
Oops, I wasn't really aware about the fact that ":memory:" is created with each new connection though it is pretty obvious once thinking about.

In #6 I went the way to make the database setting mandatory and so force the user to specify an explicit path.
I'm not sure whether defining an arbitrary default path would make things better as it might not be clear to users where the Sqlite database is written to and so this might cause confusion.

If you agree, I would merge #6 and release soonish.

**Comment by leifurhauks** [comment]
Sounds good to me!
