### ISSUE TITLE
Make a new release to have HttpTransport class in pip version

### ISSUE THREAD

**Issue by MrHalfman** [eht16/python-logstash-async#57]
Hello,

When we install the lib from pip we have the 2.0 version, which doesn't include HttpTransport class. Could you create a new release to have this transport method without doing a manual installation please?

Thank you

**Comment by eht16** [comment]
Done:
https://github.com/eht16/python-logstash-async/releases/tag/2.1.0
https://pypi.org/project/python-logstash-async/
