### ISSUE TITLE
After updateing to 2.1.0 the log events miss the *message* attribute.

### ISSUE THREAD

**Issue by ascheucher** [eht16/python-logstash-async#58]
Without any change in the logger setup the log events reaching ELK are missing the *message* attribute.
Just updated with pip.

Logs have following indication in the Kibana Message field: failed to find message
Checking the index, there are also no message field in the events.

Thanks for checking.

**Comment by eht16** [comment]
Ouch, sorry for this.

This was a regression from d2d30256370997b9406036e411b12e12aa5897f3 and got overlooked :(. I'll write unittests for the formatters.

2.1.1 is released.

**Comment by ascheucher** [comment]
No problem at all. Just wondered, whether I did something wrong on my side, as I am quiet new to the ELK stack...
Thanks for the fast fix!
