### ISSUE TITLE
Feature Request: Option to work in sync

### ISSUE THREAD

**Issue by chickahoona** [eht16/python-logstash-async#59]
First thanks for your work!

I know it sounds extremely stupid to ask for this, yet I'd like to use your lib in Psono, yet it would need Google's Cloud Run support.
A stupid thing about cloud run is, that all processes are only executed during a request and afterwards the CPU is throttled down completely. So asynchronous events may not be processed at all or are extremely delayed and Cloud Run's scaling at the end will cause potential data loss :(

A flag that would tell the logger to handle the request synchronous would be amazing, which would allow people to switch between synchronous and asynchronous processing depending on their environment.

**Comment by eht16** [comment]
It doesn't sound too stupid :). I assume you basically want to use one of the formatters and one of the transports, just without the database and asyncronous handling in between?

I guess with a bit of refactoring, this could be possible.

**Comment by chickahoona** [comment]
Exactly. I was already searching for quite some time and your library seems to be the only "good" one that supports also features like TLS that I need, so I am a bit without alternatives here.

**Comment by chickahoona** [comment]
I created a PR,  hoping that it will be accepted :)
