### ISSUE TITLE
Delay in sending logs to Logstash

### ISSUE THREAD

**Issue by chaoyifei** [eht16/python-logstash-async#66]
It looks like in case of a lot of log events (about about 1 million per day), python-logstash-async doesn't process them in time and keeps them in the queue. This leads events being pushed to logstash with a long delay(several hours in our case).

**Comment by eht16** [comment]
Could be related to #63 or at least information there could help debugging this issue.

Also, you could try playing with the queueing related settings (https://python-logstash-async.readthedocs.io/en/stable/config.html#options-for-the-asynchronous-processing-and-formatting).

**Comment by eht16** [comment]
Closing on missing response. Re-open if the problem persists.
