### ISSUE TITLE
Sqlite DB not vacuumed

### ISSUE THREAD

**Issue by cbeaujoin-stellar** [eht16/python-logstash-async#80]
The sqlite db should be vacuumed.
At shutdown for example.

**Comment by eht16** [comment]
Just implemented it and released in 2.7.0.

I was struggling with this for a long time and not sure how to implement it best. I think at shutdown is probably good.
Note that it is configurable and disabled by default, at least for now.
To enable it, set `constants.DATABASE_VACUUM_ON_SHUTDOWN` to `True`.

**Comment by cbeaujoin-stellar** [comment]
Hi Enrico,
thank you for the improvment
