### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by arossert** [eht16/python-logstash-async#82]
The latest version is not working on Windows as `fcntl` is not exists

**Comment by eht16** [comment]
It is expected and obvious that `fnctl` is not available on Windows.
I did not expect that anyone would use the library on Windows.

I will make the send buffer check optional.

For my curiosity, do you use the library on Windows in a production environment or "just" in a development environment?

**Comment by arossert** [comment]
We are also using it in production

**Comment by eht16** [comment]
Should be fixed in master (https://github.com/eht16/python-logstash-async/commit/aea33fb57734a2a092d4ad4cddbe02cacfefced3). It would be great if you could test it.

Release will follow soon.
