### ISSUE TITLE
Makes get_queued_events FIFO or LIFO

### ISSUE THREAD

**Issue by cbeaujoin-stellar** [eht16/python-logstash-async#84]
Sometime when connectivity brokes it's more interesting to retrieve the fresh data first and not the oldest ones.
A simple improvment would be to have choice between LIFO or FIFO in the DatabaseCache.get_queued_events method.

- FIFO (current) : 
```
        query_fetch = '''
            SELECT `event_id`, `event_text` FROM `event` WHERE `pending_delete` = 0 LIMIT ?;'''
```

- LIFO (should be): 
```
        query_fetch = '''
            SELECT `event_id`, `event_text` FROM `event` WHERE `pending_delete` = 0 ORDER BY `event_id` DESC LIMIT ?;'''
```

It could be enabled/disabled using a constant, ie: constants.QUEUED_EVENTS_FLUSH_LIFO = True

Call hierarchy is :
LogProcessingWorker._fetch_queued_events_for_flush >DatabaseCache.get_queued_events

**Comment by eht16** [comment]
Assuming that on subsequent push attempts, all events will be pushed shortly, I don't think it makes a big difference.

Though if you want, create a PR.
