### ISSUE TITLE
2.7.0 doesn't work under Windows

### ISSUE THREAD

**Issue by scottwday** [eht16/python-logstash-async#86]
[This commit](https://github.com/eht16/python-logstash-async/pull/81/commits/71d2e01ed22ecb9b2c3189fd59252a2f4544aa92#diff-7bf09117b5569f69479e836eca8a73b43749143d3322d8b11c693449cc95e556L8) added a dependency on fcntl which isn't present in Windows.

Resulting in `ModuleNotFoundError: No module named 'fcntl'`

I can create a PR to exclude it, but would [this issue ](https://github.com/eht16/python-logstash-async/pull/81)be present in Windows too?

**Comment by eht16** [comment]
Already reported (https://github.com/eht16/python-logstash-async/issues/82) and fixed in master. Will be released later today.

I don't know if Windows is also affected by #81. If so, PRs are welcome but I won't work on this myself.
